import { NavItem } from '@/components/dashboard-nav-mobile';

export const navItems: NavItem[] = [
  {
    title: 'Tableau de bord',
    href: '/dashboard',
    icon: 'dashboard',
    label: 'Dashboard'
  },
  {
    title: 'Utilisateurs',
    href: '/dashboard/users',
    icon: 'ShoppingBasket',
    label: 'users'
  },
  {
    title: 'Produits',
    href: '/dashboard/products',
    icon: 'ShoppingBasket',
    label: 'products'
  },
  {
    title: 'Ajouter un produit',
    href: '/dashboard/product',
    icon: 'add',
    label: 'addProduct'
  },
  {
    title: 'Commandes',
    href: '/dashboard/orders',
    icon: 'order',
    label: 'orders'
  },
  {
    title: 'Sélections spéciales',
    href: '/dashboard/highlights',
    icon: 'Gem',
    label: 'highlights'
  },
  {
    title: 'Ajouter une Sélection',
    href: '/dashboard/highlight',
    icon: 'add',
    label: 'addHighlight'
  },
  {
    title: 'Carousels',
    href: '/dashboard/carousels',
    icon: 'ImageIcon',
    label: 'carousels'
  },
  {
    title: 'Coupons',
    href: '/dashboard/coupons',
    icon: 'Receipt',
    label: 'coupons'
  },
  {
    title: 'Ajouter un coupons',
    href: '/dashboard/coupon',
    icon: 'add',
    label: 'coupons'
  },
  {
    title: 'Déconnexion',
    href: '/',
    icon: 'login',
    label: 'logOut'
  }
];

export const nationalities = [
  { value: 'Afghan', label: 'Afghan' },
  { value: 'Albanais', label: 'Albanais' },
  { value: 'Algérien', label: 'Algérien' },
  { value: 'Américain', label: 'Américain' },
  { value: 'Andorran', label: 'Andorran' },
  { value: 'Angolais', label: 'Angolais' },
  { value: 'Antiguaise', label: 'Antiguaise' },
  { value: 'Argentinien', label: 'Argentinien' },
  { value: 'Arménien', label: 'Arménien' },
  { value: 'Australien', label: 'Australien' },
  { value: 'Autrichien', label: 'Autrichien' },
  { value: 'Azerbaïdjanais', label: 'Azerbaïdjanais' },
  { value: 'Bahamais', label: 'Bahamais' },
  { value: 'Bahreïni', label: 'Bahreïni' },
  { value: 'Bangladais', label: 'Bangladais' },
  { value: 'Barbadien', label: 'Barbadien' },
  { value: 'Barbudois', label: 'Barbudois' },
  { value: 'Botswanais', label: 'Botswanais' },
  { value: 'Biélorusse', label: 'Biélorusse' },
  { value: 'Belgique', label: 'Belgique' },
  { value: 'Bélizien', label: 'Bélizien' },
  { value: 'Béninois', label: 'Béninois' },
  { value: 'Bhoutanais', label: 'Bhoutanais' },
  { value: 'Bolivien', label: 'Bolivien' },
  { value: 'Bosnien', label: 'Bosnien' },
  { value: 'Brésilien', label: 'Brésilien' },
  { value: 'Britannique', label: 'Britannique' },
  { value: 'Brunéi', label: 'Brunéi' },
  { value: 'Bulgare', label: 'Bulgare' },
  { value: 'Burkinabé', label: 'Burkinabé' },
  { value: 'Birman', label: 'Birman' },
  { value: 'Burundais', label: 'Burundais' },
  { value: 'Cambodgien', label: 'Cambodgien' },
  { value: 'Camerounais', label: 'Camerounais' },
  { value: 'Canadien', label: 'Canadien' },
  { value: 'Cap-Verdien', label: 'Cap-Verdien' },
  { value: 'Centrafricain', label: 'Centrafricain' },
  { value: 'Tchadien', label: 'Tchadien' },
  { value: 'Chilien', label: 'Chilien' },
  { value: 'Chinois', label: 'Chinois' },
  { value: 'Colombien', label: 'Colombien' },
  { value: 'Comorien', label: 'Comorien' },
  { value: 'Congolais', label: 'Congolais' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Croate', label: 'Croate' },
  { value: 'Cubaine', label: 'Cubaine' },
  { value: 'Chypriote', label: 'Chypriote' },
  { value: 'Tchèque', label: 'Tchèque' },
  { value: 'Danois', label: 'Danois' },
  { value: 'Djiboutien', label: 'Djiboutien' },
  { value: 'Dominicain', label: 'Dominicain' },
  { value: 'Néerlandais', label: 'Néerlandais' },
  { value: 'Estonien', label: 'Estonien' },
  { value: 'Éthiopien', label: 'Éthiopien' },
  { value: 'Fidjien', label: 'Fidjien' },
  { value: 'Philippin', label: 'Philippin' },
  { value: 'Finlandais', label: 'Finlandais' },
  { value: 'Français', label: 'Français' },
  { value: 'Japonais', label: 'Japonais' },
  { value: 'Gambien', label: 'Gambien' },
  { value: 'Géorgien', label: 'Géorgien' },
  { value: 'Allemand', label: 'Allemand' },
  { value: 'Ghanéen', label: 'Ghanéen' },
  { value: 'Grec', label: 'Grec' },
  { value: 'Grenadien', label: 'Grenadien' },
  { value: 'Guatémaltèque', label: 'Guatémaltèque' },
  { value: 'Guinéen Bissau', label: 'Guinéen Bissau' },
  { value: 'Guinéen', label: 'Guinéen' },
  { value: 'Guyanais', label: 'Guyanais' },
  { value: 'Haïtien', label: 'Haïtien' },
  { value: 'Harsi', label: 'Harsi' },
  { value: 'Hondurien', label: 'Hondurien' },
  { value: 'Hongrois', label: 'Hongrois' },
  { value: 'Islandais', label: 'Islandais' },
  { value: 'Indien', label: 'Indien' },
  { value: 'Indonésien', label: 'Indonésien' },
  { value: 'Iranien', label: 'Iranien' },
  { value: 'Iraquien', label: 'Iraquien' },
  { value: 'Irlandais', label: 'Irlandais' },
  { value: 'Italien', label: 'Italien' },
  { value: 'Ivoirien', label: 'Ivoirien' },
  { value: 'Jamaïcain', label: 'Jamaïcain' },
  { value: 'Japonais', label: 'Japonais' },
  { value: 'Jordanien', label: 'Jordanien' },
  { value: 'Kazakh', label: 'Kazakh' },
  { value: 'Kényan', label: 'Kényan' },
  { value: 'Kittitien et Névisien', label: 'Kittitien et Névisien' },
  { value: 'Koweïtiens', label: 'Koweïtiens' },
  { value: 'Kirghiz', label: 'Kirghiz' },
  { value: 'Laotien', label: 'Laotien' },
  { value: 'Letton', label: 'Letton' },
  { value: 'Libanais', label: 'Libanais' },
  { value: 'Libérien', label: 'Libérien' },
  { value: 'Libyen', label: 'Libyen' },
  { value: 'Liechtensteinois', label: 'Liechtensteinois' },
  { value: 'Lituanien', label: 'Lituanien' },
  { value: 'Luxembourgeois', label: 'Luxembourgeois' },
  { value: 'Macédonien', label: 'Macédonien' },
  { value: 'Malgache', label: 'Malgache' },
  { value: 'Malawien', label: 'Malawien' },
  { value: 'Malaisien', label: 'Malaisien' },
  { value: 'Maldivien', label: 'Maldivien' },
  { value: 'Malien', label: 'Malien' },
  { value: 'Maltais', label: 'Maltais' },
  { value: 'Marshallais', label: 'Marshallais' },
  { value: 'Mauritanien', label: 'Mauritanien' },
  { value: 'Mauricien', label: 'Mauricien' },
  { value: 'Mexicain', label: 'Mexicain' },
  { value: 'Micronésien', label: 'Micronésien' },
  { value: 'Moldave', label: 'Moldave' },
  { value: 'Monégasque', label: 'Monégasque' },
  { value: 'Mongol', label: 'Mongol' },
  { value: 'Marocain', label: 'Marocain' },
  { value: 'Lesothan', label: 'Lesothan' },
  { value: 'Leswaï', label: 'Leswaï' },
  { value: 'Mozambicain', label: 'Mozambicain' },
  { value: 'Namibien', label: 'Namibien' },
  { value: 'Nauruan', label: 'Nauruan' },
  { value: 'Népalais', label: 'Népalais' },
  { value: 'Néerlandais', label: 'Néerlandais' },
  { value: 'Néo-Zélandais', label: 'Néo-Zélandais' },
  { value: 'Nicaraguayen', label: 'Nicaraguayen' },
  { value: 'Nigérian', label: 'Nigérian' },
  { value: 'Nigerianien', label: 'Nigerianien' },
  { value: 'Norvégien', label: 'Norvégien' },
  { value: 'Omanais', label: 'Omanais' },
  { value: 'Pakistanais', label: 'Pakistanais' },
  { value: 'Palawaï', label: 'Palawaï' },
  { value: 'Béninois', label: 'Béninois' },
  { value: 'Bébopoians', label: 'Bébopoians' },
  { value: 'Paraguayen', label: 'Paraguayen' },
  { value: 'Péruvien', label: 'Péruvien' },
  { value: 'Philippin', label: 'Philippin' },
  { value: 'Palestinien', label: 'Palestinien' },
  { value: 'Polonais', label: 'Polonais' },
  { value: 'Portugais', label: 'Portugais' },
  { value: 'Qatarien', label: 'Qatarien' },
  { value: 'Russe', label: 'Russe' },
  { value: 'Rwandais', label: 'Rwandais' },
  { value: 'Samoanais', label: 'Samoanais' },
  { value: 'Saint-Marinais', label: 'Saint-Marinais' },
  { value: 'Saoudien', label: 'Saoudien' },
  { value: 'Sénégalais', label: 'Sénégalais' },
  { value: 'Serbe', label: 'Serbe' },
  { value: 'Seychellois', label: 'Seychellois' },
  { value: 'Singapourien', label: 'Singapourien' },
  { value: 'Slovaque', label: 'Slovaque' },
  { value: 'Slovène', label: 'Slovène' },
  { value: 'Somalien', label: 'Somalien' },
  { value: 'Sud-Africain', label: 'Sud-Africain' },
  { value: 'Espagnol', label: 'Espagnol' },
  { value: 'Sri-Lankais', label: 'Sri-Lankais' },
  { value: 'Soudanais', label: 'Soudanais' },
  { value: 'Surinamien', label: 'Surinamien' },
  { value: 'Suédois', label: 'Suédois' },
  { value: 'Suisse', label: 'Suisse' },
  { value: 'Syrien', label: 'Syrien' },
  { value: 'Taïwanais', label: 'Taïwanais' },
  { value: 'Tadjik', label: 'Tadjik' },
  { value: 'Tanzanien', label: 'Tanzanien' },
  { value: 'Thaïlandais', label: 'Thaïlandais' },
  { value: 'Togolais', label: 'Togolais' },
  { value: 'Tunisien', label: 'Tunisien' },
  { value: 'Turc', label: 'Turc' },
  { value: 'Turkmène', label: 'Turkmène' },
  { value: 'Ougandais', label: 'Ougandais' },
  { value: 'Ukrainien', label: 'Ukrainien' },
  { value: 'Uruguayen', label: 'Uruguayen' },
  { value: 'Ouzbek', label: 'Ouzbek' },
  { value: 'Vanuatuais', label: 'Vanuatuais' },
  { value: 'Vénézuélien', label: 'Vénézuélien' },
  { value: 'Vietnamien', label: 'Vietnamien' },
  { value: 'Zambien', label: 'Zambien' },
  { value: 'Zimbabween', label: 'Zimbabween' }
];
